apiVersion: apps/v1
kind: Deployment
metadata:
 name: k8s-bigip1-ctlr-deployment
 namespace: kube-system
spec:
 selector:
   matchLabels:
     app: k8s-bigip1-ctlr
 # DO NOT INCREASE REPLICA COUNT
 replicas: 1
 template:
   metadata:
     labels:
       app: k8s-bigip1-ctlr
   spec:
     # Name of the Service Account bound to a Cluster Role with the required
     # permissions
     serviceAccountName: bigip-ctlr
     containers:
       - name: k8s-bigip-ctlr
         image: "f5networks/k8s-bigip-ctlr:latest"
         env:
           - name: BIGIP_USERNAME
             valueFrom:
               secretKeyRef:
                 # Replace with the name of the Secret containing your login
                 # credentials
                 name: bigip-login
                 key: username
           - name: BIGIP_PASSWORD
             valueFrom:
               secretKeyRef:
                 # Replace with the name of the Secret containing your login
                 # credentials
                 name: bigip-login
                 key: password
         command: ["/app/bin/k8s-bigip-ctlr"]
         args: [
              "--bigip-username=$(BIGIP_USERNAME)",
              "--bigip-password=$(BIGIP_PASSWORD)",
              # Replace with the IP address or hostname of your BIG-IP device
              "--bigip-url=10.1.20.5",
              # Replace with the name of the BIG-IP partition you want to manage
              "--bigip-partition=kubernetes",
              # Replace with service type - cluster or nodeport
              "--pool-member-type=cluster",
              # Logging level
              "--log-level=DEBUG",
              "--log-as3-response=true",
              # Self-signed cert
              "--insecure=true",
              # Custom Resource Mode
              "--custom-resource-mode=true"
            ]
        imagePullSecrets:
          - name: f5-docker-images
          - name: bigip-login