apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-hello-world-web2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f5-hello-world-web2
  template:
    metadata:
      labels:
        app: f5-hello-world-web2
    spec:
      containers:
      - env:
        - name: service_name
          value: f5-hello-world-web2
        image: f5devcentral/f5-hello-world:latest
        imagePullPolicy: Always
        name: f5-hello-world-web2
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: f5-hello-world-web2
  namespace: default
  labels:
    app: f5-hello-world-web2
    cis.f5.com/as3-tenant: AS3_2
    cis.f5.com/as3-app: A2
    cis.f5.com/as3-pool: web_pool2
spec:
  ports:
  - name: f5-hello-world-web2
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: f5-hello-world-web2
